# Generated by Django 4.1.3 on 2022-12-01 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('business_name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('business_type', models.CharField(max_length=40, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('sector', models.CharField(max_length=200, null=True)),
                ('latitude', models.FloatField(default=0, null=True)),
                ('longitude', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='statuses',
            fields=[
                ('status_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='service_detail',
            fields=[
                ('services_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('service_type', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('request_sender', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(default='0', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmed.statuses')),
            ],
        ),
    ]
