# Generated by Django 4.1.3 on 2022-11-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='cell',
            new_name='district',
        ),
    ]
