# Generated by Django 4.1.3 on 2022-12-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmed', '0006_rename_service_service_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_detail',
            name='id',
        ),
        migrations.AddField(
            model_name='service_detail',
            name='services_id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service_detail',
            name='description',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='service_detail',
            name='name',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='service_detail',
            name='type',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
